import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    const cars = [
        {
            licensePlate: 'ABC-123',
            brand: 'Chevrolet',
            model: 'Malibu',
            manufactureYear: 2020,
            pricePerHour: 45.00,
            mileage: 30000,
            carType: 'Sedan',
            capacity: 5,
            color: 'White',
            description: 'Mid-size sedan with good fuel efficiency.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Chevrolet-Malibu_fibsgv.png',
            publicImageId: 'Chevrolet-Malibu_fibsgv',
        },
        {
            licensePlate: 'XYZ-789',
            brand: 'Chevrolet',
            model: 'Traverse',
            manufactureYear: 2022,
            pricePerHour: 75.00,
            mileage: 18000,
            carType: 'SUV',
            capacity: 7,
            color: 'Silver',
            description: 'Spacious SUV, perfect for families.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Chevrolet-Traverse_urll2d.png',
            publicImageId: 'Chevrolet-Traverse_urll2d',
        },
        {
            licensePlate: 'FTR-456',
            brand: 'Ford',
            model: 'Raptor',
            manufactureYear: 2021,
            pricePerHour: 90.00,
            mileage: 40000,
            carType: 'Pickup',
            capacity: 5,
            color: 'Gray',
            description: 'Powerful off-road pickup truck.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Ford-Raptor_kl9vk8.png',
            publicImageId: 'Ford-Raptor_kl9vk8',
        },
        {
            licensePlate: 'HND-321',
            brand: 'Honda',
            model: 'Civic',
            manufactureYear: 2023,
            pricePerHour: 50.00,
            mileage: 12000,
            carType: 'Sedan',
            capacity: 5,
            color: 'Silver',
            description: 'Reliable compact sedan with modern features.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Honda-Civic_ldcib2.png',
            publicImageId: 'Honda-Civic_ldcib2',
        },
        {
            licensePlate: 'CRV-555',
            brand: 'Honda',
            model: 'CR-V',
            manufactureYear: 2022,
            pricePerHour: 65.00,
            mileage: 22000,
            carType: 'SUV',
            capacity: 5,
            color: 'Blue',
            description: 'Comfortable and efficient crossover SUV.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980555/Honda-CRV_zvdsuq.png',
            publicImageId: 'Honda-CRV_zvdsuq',
        },
        {
            licensePlate: 'IFX-888',
            brand: 'Infiniti',
            model: 'QX80',
            manufactureYear: 2023,
            pricePerHour: 110.00,
            mileage: 15000,
            carType: 'SUV',
            capacity: 7,
            color: 'Black',
            description: 'Luxury full-size SUV with premium features.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980555/Infiniti-QX80_se6mro.png',
            publicImageId: 'Infiniti-QX80_se6mro',
        },
        {
            licensePlate: 'KIA-678',
            brand: 'Kia',
            model: 'Sedona',
            manufactureYear: 2021,
            pricePerHour: 70.00,
            mileage: 30000,
            carType: 'MPV',
            capacity: 7,
            color: 'Blue',
            description: 'Spacious minivan with sliding doors.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Kia-Sedona_nhetid.png',
            publicImageId: 'Kia-Sedona_nhetid',
        },
        {
            licensePlate: 'AUD-444',
            brand: 'Audi',
            model: 'Q8',
            manufactureYear: 2022,
            pricePerHour: 130.00,
            mileage: 10000,
            carType: 'SUV',
            capacity: 5,
            color: 'White',
            description: 'Sporty and luxurious SUV coupe.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980555/Audi-Q8_fsfzxq.png',
            publicImageId: 'Audi-Q8_fsfzxq',
        },
        {
            licensePlate: 'BMW-007',
            brand: 'BMW',
            model: 'X5',
            manufactureYear: 2023,
            pricePerHour: 140.00,
            mileage: 8000,
            carType: 'SUV',
            capacity: 5,
            color: 'Black',
            description: 'High-performance luxury SUV.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980555/BMW-X5_ll1miv.png',
            publicImageId: 'BMW-X5_ll1miv',
        },
        {
            licensePlate: 'CRZ-999',
            brand: 'Chevrolet',
            model: 'Cruze',
            manufactureYear: 2020,
            pricePerHour: 40.00,
            mileage: 35000,
            carType: 'Sedan',
            capacity: 5,
            color: 'Silver',
            description: 'Compact and fuel-efficient daily driver.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Chevrolet-Cruze_kaakfx.png',
            publicImageId: 'Chevrolet-Cruze_kaakfx',
        },
        {
            licensePlate: 'MBZ-001',
            brand: 'Mercedes-Benz',
            model: 'GLC',
            manufactureYear: 2022,
            pricePerHour: 125.00,
            mileage: 15000,
            carType: 'SUV',
            capacity: 5,
            color: 'Gray',
            description: 'Luxury compact SUV with advanced features.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Mercedes-Benz-GLC_n4hgrh.png',
            publicImageId: 'Mercedes-Benz-GLC_n4hgrh',
        },
        {
            licensePlate: 'MIT-002',
            brand: 'Mitsubishi',
            model: 'Outlander',
            manufactureYear: 2023,
            pricePerHour: 70.00,
            mileage: 10000,
            carType: 'SUV',
            capacity: 7,
            color: 'Silver',
            description: 'Versatile family SUV with modern styling.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Mitsubishi-Outlander_i34qh3.png',
            publicImageId: 'Mitsubishi-Outlander_i34qh3',
        },
        {
            licensePlate: 'MIT-003',
            brand: 'Mitsubishi',
            model: 'Xpander',
            manufactureYear: 2023,
            pricePerHour: 60.00,
            mileage: 9000,
            carType: 'MPV',
            capacity: 7,
            color: 'Silver',
            description: 'Compact MPV with 7-seat configuration.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Mitsubishi-Xpander_kzwdkb.png',
            publicImageId: 'Mitsubishi-Xpander_kzwdkb',
        },
        {
            licensePlate: 'NSN-004',
            brand: 'Nissan',
            model: 'Rogue',
            manufactureYear: 2022,
            pricePerHour: 68.00,
            mileage: 13000,
            carType: 'SUV',
            capacity: 5,
            color: 'Gray',
            description: 'Efficient and stylish urban SUV.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Nissan-Rogue_nr9bsl.png',
            publicImageId: 'Nissan-Rogue_nr9bsl',
        },
        {
            licensePlate: 'PEU-005',
            brand: 'Peugeot',
            model: '508',
            manufactureYear: 2023,
            pricePerHour: 95.00,
            mileage: 11000,
            carType: 'Sedan',
            capacity: 5,
            color: 'Gray',
            description: 'Sleek European sedan with luxury interior.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980558/Peugeot-508_entasb.png',
            publicImageId: 'Peugeot-508_entasb',
        },
        {
            licensePlate: 'KGG-006',
            brand: 'Koenigsegg',
            model: 'Agera RS',
            manufactureYear: 2021,
            pricePerHour: 1000.00,
            mileage: 7000,
            carType: 'Sport',
            capacity: 2,
            color: 'White',
            description: 'Hypercar with extreme performance and rarity.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Koenigsegg-AgeraRS_reevsl.png',
            publicImageId: 'Koenigsegg-AgeraRS_reevsl',
        },
        {
            licensePlate: 'MZD-007',
            brand: 'Mazda',
            model: 'Mazda3',
            manufactureYear: 2022,
            pricePerHour: 55.00,
            mileage: 14000,
            carType: 'Hatchback',
            capacity: 5,
            color: 'Gray',
            description: 'Stylish hatchback with sporty handling.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Mazda-Mazda3_vfbfge.png',
            publicImageId: 'Mazda-Mazda3_vfbfge',
        },
        {
            licensePlate: 'MZD-008',
            brand: 'Mazda',
            model: 'CX-5',
            manufactureYear: 2023,
            pricePerHour: 72.00,
            mileage: 8000,
            carType: 'SUV',
            capacity: 5,
            color: 'Gray',
            description: 'Popular crossover with premium features.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980556/Mazda-CX5_suikmx.png',
            publicImageId: 'Mazda-CX5_suikmx',
        },
        {
            licensePlate: 'MZD-009',
            brand: 'Mazda',
            model: 'MX-5',
            manufactureYear: 2021,
            pricePerHour: 85.00,
            mileage: 20000,
            carType: 'Sport',
            capacity: 2,
            color: 'Red',
            description: 'Iconic roadster with top-down driving fun.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Mazda-MX5_ykxgha.png',
            publicImageId: 'Mazda-MX5_ykxgha',
        },
        {
            licensePlate: 'MBZ-010',
            brand: 'Mercedes-Benz',
            model: 'C300',
            manufactureYear: 2022,
            pricePerHour: 120.00,
            mileage: 16000,
            carType: 'Sedan',
            capacity: 5,
            color: 'Silver',
            description: 'Luxury sedan with elegant design.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980557/Mercedes-Benz-C300_qzswsz.png',
            publicImageId: 'Mercedes-Benz-C300_qzswsz',
        },
        {
            licensePlate: 'RRR-001',
            brand: 'Rolls-Royce',
            model: 'Phantom',
            manufactureYear: 2021,
            pricePerHour: 1500.00,
            mileage: 9000,
            carType: 'Ultra Luxury Sedan',
            capacity: 4,
            color: 'Black',
            description: 'Ultra-luxury sedan with handcrafted excellence.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980562/RollsRoyce-Phantom_ntefis.png',
            publicImageId: 'RollsRoyce-Phantom_ntefis',
        },
        {
            licensePlate: 'TYT-002',
            brand: 'Toyota',
            model: 'Camry',
            manufactureYear: 2022,
            pricePerHour: 60.00,
            mileage: 10000,
            carType: 'Sedan',
            capacity: 5,
            color: 'White',
            description: 'Comfortable and reliable family sedan.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980562/Toyota-Camry_hmucjg.png',
            publicImageId: 'Toyota-Camry_hmucjg',
        },
        {
            licensePlate: 'TYT-003',
            brand: 'Toyota',
            model: 'Innova',
            manufactureYear: 2023,
            pricePerHour: 65.00,
            mileage: 8000,
            carType: 'MPV',
            capacity: 7,
            color: 'Blue',
            description: 'Popular 7-seater MPV for group travel.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980563/Toyota-Innova_ywruf6.png',
            publicImageId: 'Toyota-Innova_ywruf6',
        },
        {
            licensePlate: 'VFS-004',
            brand: 'VinFast',
            model: 'VF e34',
            manufactureYear: 2023,
            pricePerHour: 55.00,
            mileage: 6000,
            carType: 'SUV',
            capacity: 5,
            color: 'Red',
            description: 'Electric SUV with modern Vietnamese design.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980564/VinFast-VFe34_xorpog.png',
            publicImageId: 'VinFast-VFe34_xorpog',
        },
        {
            licensePlate: 'VFS-005',
            brand: 'VinFast',
            model: 'VF 8',
            manufactureYear: 2023,
            pricePerHour: 70.00,
            mileage: 7000,
            carType: 'SUV',
            capacity: 5,
            color: 'Black',
            description: 'Stylish electric SUV with cutting-edge tech.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980564/VinFast-VF8_bva6yv.png',
            publicImageId: 'VinFast-VF8_bva6yv',
        },
        {
            licensePlate: 'PEU-006',
            brand: 'Peugeot',
            model: '3008',
            manufactureYear: 2022,
            pricePerHour: 78.00,
            mileage: 9500,
            carType: 'SUV',
            capacity: 5,
            color: 'Brown',
            description: 'French SUV with modern design and comfort.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980558/Peugeot-3008_fqdkzw.png',
            publicImageId: 'Peugeot-3008_fqdkzw',
        },
        {
            licensePlate: 'PRC-007',
            brand: 'Porsche',
            model: 'Cayenne',
            manufactureYear: 2022,
            pricePerHour: 180.00,
            mileage: 12000,
            carType: 'SUV',
            capacity: 5,
            color: 'Gray',
            description: 'High-performance luxury SUV from Porsche.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980558/Porsche-Cayenne_ohi1iy.png',
            publicImageId: 'Porsche-Cayenne_ohi1iy',
        },
        {
            licensePlate: 'PRC-008',
            brand: 'Porsche',
            model: 'Taycan',
            manufactureYear: 2023,
            pricePerHour: 220.00,
            mileage: 5000,
            carType: 'Electric',
            capacity: 4,
            color: 'Purple',
            description: 'Electric sports car with stunning acceleration.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980561/Porsche-Taycan_zjglgc.png',
            publicImageId: 'Porsche-Taycan_zjglgc',
        },
        {
            licensePlate: 'RRV-009',
            brand: 'Range Rover',
            model: 'Sport Dynamic SE',
            manufactureYear: 2023,
            pricePerHour: 200.00,
            mileage: 7000,
            carType: 'SUV',
            capacity: 5,
            color: 'White',
            description: 'Luxury SUV with sporty handling and design.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980562/RangeRover-SportDynamicSE_n7ftwe.png',
            publicImageId: 'RangeRover-SportDynamicSE_n7ftwe',
        },
        {
            licensePlate: 'RRV-010',
            brand: 'Range Rover',
            model: 'Evoque',
            manufactureYear: 2021,
            pricePerHour: 110.00,
            mileage: 15000,
            carType: 'SUV',
            capacity: 5,
            color: 'Red',
            description: 'Compact luxury SUV with sleek lines.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980561/RangeRover-Evoque_vd8chq.png',
            publicImageId: 'RangeRover-Evoque_vd8chq',
        },
        {
            licensePlate: 'VLV-011',
            brand: 'Volvo',
            model: 'S90',
            manufactureYear: 2022,
            pricePerHour: 115.00,
            mileage: 9000,
            carType: 'Sedan',
            capacity: 5,
            color: 'Silver',
            description: 'Elegant Scandinavian sedan with luxury and safety.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980564/Volvo-S90_ladmz1.png',
            publicImageId: 'Volvo-S90_ladmz1',
        },
        {
            licensePlate: 'TYT-012',
            brand: 'Toyota',
            model: 'Yaris',
            manufactureYear: 2020,
            pricePerHour: 42.00,
            mileage: 25000,
            carType: 'Hatchback',
            capacity: 5,
            color: 'White',
            description: 'Compact hatchback ideal for city driving.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980564/Toyota-Yaris_ackc7r.png',
            publicImageId: 'Toyota-Yaris_ackc7r',
        },
        {
            licensePlate: 'PRC-013',
            brand: 'Porsche',
            model: 'Panamera',
            manufactureYear: 2025,
            pricePerHour: 250.00,
            mileage: 2000,
            carType: 'Coupe',
            capacity: 4,
            color: 'Brown',
            description: 'Luxury sports sedan with high-end performance.',
            imagePath: 'https://res.cloudinary.com/dyfdj1ifv/image/upload/v1763980558/Porsche-Panamera_nzimoc.png',
            publicImageId: 'Porsche-Panamera_nzimoc',
        },
    ];

    for (const car of cars) {
        await prisma.car.create({ data: car });
    }
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });